##########################################################Colors ################################################## 
Bl="\[\033[0;30m\]" # Black
Re="\[\033[0;31m\]" # Red
Gr="\[\033[0;32m\]" # Green
Ye="\[\033[0;33m\]" # Yellow
Bu="\[\033[0;34m\]" # Blue
Pu="\[\033[0;35m\]" # Purple
Cy="\[\033[0;36m\]" # Cyan
Wh="\[\033[0;37m\]" # White

#############################libarary#################################################################
import compileall
import socket
import os
from time import sleep as timeout
import time
from V7xStyle import Animation

################################################################################################################################################################

############################################################# termux_tool #############################################################################

def termux_tool() :

    Done()
    time.sleep(0.7)
    os.system('clear')
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;34m||                      1. Lazymux Tool                 ||")
    time.sleep(0.2)
    print ("|\033[0;31m|                                                      ||")
    time.sleep(0.2)
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;34m||                      2. DarkFly-Tool                 ||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;34m||                      3. WEEMAN                       ||") 
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;34m||                     4. Termux TXTool                 ||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;34m||                     5. F.E.D.O.R.A                   ||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;34m||                    6. Termux Tool X                  ||")
    time.sleep(0.2)
    print ("|\033[0;31m|                                                      ||")
    time.sleep(0.2)
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;34m||                    7. DevploitTool                   ||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;34m||                    8. Optiva Tool                    ||") 
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;34m||                   9. Fsociety Tool                   ||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;34m||                   10. Speed  Test                    ||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;34m||                   11. WiFi  Scan                     ||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;34m||                   12. WiFi  Info                     ||")
    time.sleep(0.2)
    print ("|\033[0;31m|                                                      ||")
    time.sleep(0.2)
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;34m||                   13. Wifite Tool                    ||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;34m||                   14. Play Media                     ||") 
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;34m||                   15. WPS BREAKER  m                 ||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;34m||                   16. Sensor Info                    ||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;34m||                   17. My  Location                   ||")
    time.sleep(0.2)
    print ("|\033[0;31m|                                                      ||")
    time.sleep(0.2)
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;34m||                   18. Scan Media                     ||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;34m||                   19. Take a Photo                   ||") 
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;34m||                   20. Lazy Script                    ||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;34m||                   21. Striker Tool                   ||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;34m||                   22. Map - SCII                     ||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;34m||                   23. Knock  Py                      ||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;34m||                   24. Knock Mail                     ||") 
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;34m||                   25. Ip GLocation                   ||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;34m||                     26. HUNNER Tool                  ||")
    time.sleep(0.2)
    print ("|\033[0;31m|                                                      ||")
    time.sleep(0.2)
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;34m||                     27. HAKKU Tool                   ||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;34m||                     28. GoBlin Tool                  ||") 
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;34m||                    29. GLooM Tool                    ||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;34m||                    30. Fluxion Tool                  ||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;34m||                   31. Zip - Unzip                    ||")
    time.sleep(0.2)
    print ("|\033[0;31m|                                                      ||")
    time.sleep(0.2)
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;34m||                   32. COMMIX Tool                    ||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;34m||                    33. Angry Fuzzer                  ||") 
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;34m||                  34. BreacherTool                    ||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;34m||                   35. BRUTAL Tool                    ||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;34m||                   36. Auto Pixie                     ||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;34m||                   37. UBUNTU Tool                    ||")
    time.sleep(0.2)
    print ("|\033[0;31m|                                                      ||")
    time.sleep(0.2)
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;34m||                   38. NGROK                          ||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;34m||                   39. Alpine -ARM                    ||") 
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;34m||                   40. WPS BREAKER  m                 ||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;34m||                   41. M.I.T.M Tool                   ||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;34m||                   42. Evil Twins                     ||")
    time.sleep(0.2)
    print ("|\033[0;31m|                                                      ||")
    time.sleep(0.2)
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;34m||                   43. REAVER WPS                     ||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;34m||                   44. HT-WPS Tool                    ||") 
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;34m||                   45. SHODAN Tool                    ||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;34m||                   46. A Rat Tool                     ||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;34m||                   47. Beef Tool                      ||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;34m||                   48. Ohmyzsh                        ||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;34m||                   49. Spammer Grab                   ||") 
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;34m||                   50. Termus Style                   ||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;34m||                   51. V7x-Tool                       ||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;34m||                   99. main                           ||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    print (" ")
    termux = input ("\033[0;36mchoice ,2,3,4,5,6,7,8,9,...... =========>>> \033[0;31m")
    if termux == '1' :
        os.system ('clear')
        print ("Loading..........!")
        print (' ')
        khaled()
        timeout(1)
        print ("done.....")
        os.system ('clear')
        os.system ('apt update && apt upgrade -y')
        os.system ('clear')
        os.system ('pkg update')
        os.system ('clear')
        os.system ('git clone https://github.com/Gameye98/Lazymux')
        os.system ('mv Lazymux ~')
        os.system ('clear')
        termux_tool()
    elif termux == '3' :
        os.system ('clear')
        print ("Loading..........!")
        khaled()
        timeout(1)
        print ('Done...')
        os.system ('clear')
        os.system ('git clone https://github.com/sabri-zaki/EasY_HaCk')
        os.system ('mv EasY_HaCk ~')
        termux_tool()
    elif termux == '4' :
        os.system ('clear')
        print ("Loading..........!")
        khaled()
        timeout(1)
        print ("done.....")
        os.system ('clear')
        os.system ('git clone https://github.com/kuburan/txtool.git')
        os.system ('mv txttool ~')

        termux_tool()
    elif termux == '5' :
        os.system ('clear')
        print ("Loading..........!")
        khaled()
        timeout(1)
        print ("done.....")
        os.system ('clear')
        os.system ('git clone https://github.com/nmilosev/termux-fedora.git')
        os.system ('mv termux-fedora.git ~')

        termux_tool()
    elif termux == '6' :
        os.system ('clear')
        print ("Loading..........!")
        khaled()
        timeout(1)
        print ("done.....")
        os.system ('clear')
        os.system ('git clone https://github.com/Rajkumrdusad/Tool-X.git')
        os.system ('mv Tool-X.git ~')

        termux_tool()
    elif termux == '7' :
        os.system ('clear')
        print ("Loading..........!")
        khaled()
        timeout(1)
        print ("done.....")
        os.system ('clear')
        os.system ('git clone https://github.com/joker25000/Devploit')
        os.system ('mv Devploit ~')

        termux_tool()
    elif termux == '8' :
        os.system ('clear')
        print ("Loading..........!")
        khaled()
        timeout(1)
        print ("done.....")
        os.system ('clear')
        os.system ('git clone https://github.com/joker25000/Optiva-Framework')
        os.system ('mv Optiva-Framework ~')

        termux_tool()
    elif termux == '9' :
        os.system ('clear')
        print ("Loading..........!")
        timeout(1)
        khaled()
        print ("done.....")
        os.system ('clear')
        os.system ('git clone https://github.com/Manisso/fsociety.git')
        os.system ('mv fsociety.git ~')

        termux_tool()
    elif termux == '10' :
        os.system ('clear')
        print ("Loading..........!")
        timeout(1)
        khaled()
        print ("done.....")
        os.system ('clear')
        os.system ('git clone https://github.com/adolfintel/speedtest.git')
        os.system ('mv speedtest.git ~')

        termux_tool()
    elif termux == '11' :
        os.system ('clear')
        print ("Loading..........!")
        timeout(1)
        khaled()
        print ("done.....")
        os.system ('clear')
        os.system ('git clone https://github.com/bmegli/wifi-scan.git')
        os.system ('mv wifi-scan.git ~')

        termux_tool()
    elif termux == '12' :
        os.system ('clear')
        print ("Loading..........!")
        timeout(1)
        khaled()
        print ("done.....")
        os.system ('clear')
        os.system ('git clone https://github.com/UbuntuForums/wireless-info.git')
        os.system ('mv wireless-info.git ~')

        termux_tool()
    elif termux == '13' :
        os.system ('clear')
        print ("Loading..........!")
        timeout(1)
        khaled()
        print ("done.....")
        os.system ('clear')
        os.system ('git clone https://github.com/derv82/wifite.git')
        os.system ('mv wifite.git ~')

        termux_tool()
    elif termux == '14' :
        os.system ('clear')
        print ("Loading..........!")
        timeout(1)
        khaled()
        print ("done.....")
        os.system ('clear')
        print ('In Google Play Store, besides installing the Termux app, also install "Termux:API" app. ')
        print ('Please Wait...')
        time.sleep(2)
        os.system ('apt update && apt upgrade -y')
        os.system ('apt install termux-api')
        print ('USE > $termux-media-player [command] [args] ')
        time.sleep(2)

        termux_tool()
    elif termux == '15' :
        os.system ('clear')
        print ("Loading..........!")
        timeout(1)
        khaled()
        print ("done.....")
        os.system ('clear')
        os.system ('git clone https://github.com/SilentGhostX/HT-WPS-Breaker.git')
        os.system ('mv HT-WPS-Breaker.git ~ ')

        termux_tool()
    elif termux == '16' :
        os.system ('clear')
        print ("Loading..........!")
        timeout(1)
        khaled()
        print ("done.....")
        os.system ('clear')
        os.system ('git clone https://github.com/intel/websensor-sensor-info.git')
        os.system ('mv websensor-sensor-info.git ~')

        termux_tool()
    elif termux == '17' :
        os.system ('clear')
        print ("Loading..........!")
        timeout(1)
        khaled()
        print ("done.....")
        os.system ('clear')
        os.system ('git clone https://github.com/abdularis/Track-My-Location.git')
        os.system ('mv Track-My-Location.git ~')

        termux_tool()
    elif termux == '18' :
        os.system ('clear')
        print ("Loading..........!")
        timeout(1)
        khaled()
        print ("done.....")
        os.system ('clear')
        os.system ('git clone https://github.com/nrkno/tv-automation-media-scanner.git')
        os.system ('mv tv-automation-media-scanner.git ~')

        termux_tool()
    elif termux == '19' :
        os.system ('clear')
        print ("Loading..........!")
        timeout(1)
        khaled()
        print ("done.....")
        os.system ('clear')
        os.system ('git clone https://github.com/botyourbusiness/android-camera2-secret-picture-taker.git')

        termux_tool()
    elif termux == '20' :
        os.system ('clear')
        print ("Loading..........!")
        timeout(1)
        khaled()
        print ("done.....")
        os.system ('clear')
        os.system ('git clone https://github.com/arismelachroinos/lscript.git')
        os.system ('mv lscript.git ~')

        termux_tool()
    elif termux == '21' :
        os.system ('clear')
        print ("Loading..........!")
        timeout(1)
        khaled()
        print ("done.....")
        os.system ('clear')
        os.system ('git clone https://github.com/s0md3v/Striker.git')
        os.system ('mv striker.git ~')

        termux_tool()
    elif termux == '22' :
        os.system ('clear')
        print ("Loading..........!")
        timeout(1)
        khaled()
        print ("done.....")
        os.system ('clear')
        os.system ('git clone https://github.com/rastapasta/mapscii')
        os.system ('mv mapscii ~')

        termux_tool()
    elif termux == '23' :
        os.system ('clear')
        print ("Loading..........!")
        timeout(1)
        khaled()
        print ("done.....")
        os.system ('clear')
        os.system ('git clone https://github.com/santiko/KnockPy/blob/master/modules/knockcore.py')
        os.system ('mv knockcore.py ~')

        termux_tool()
    elif termux == '24' :
        os.system ('clear')
        print ("Loading..........!")
        timeout(1)
        khaled()
        print ("done.....")
        os.system ('clear')
        os.system ('git clone https://github.com/guelfoweb/knock')
        os.system ('mv knock ~')

        termux_tool()
    elif termux == '25' :
        os.system ('clear')
        print ("Loading..........!")
        timeout(1)
        khaled()
        print ("done.....")
        os.system ('clear')
        os.system ('git clone https://github.com/maldevel/IPGeoLocation')
        os.system ('mv IPGeoLocation ~')

        termux_tool()
    elif termux == '26' :
        os.system ('clear')
        print ("Loading..........!")
        timeout(1)
        khaled()
        print ("done.....")
        os.system ('clear')
        os.system ('git clone https://github.com/b3-v3r/Hunner')
        os.system ('mv Hunner ~')

        termux_tool()
    elif termux == '27' :
        os.system ('clear')
        print ("Loading..........!")
        timeout(1)
        khaled()
        print ("done.....")
        os.system ('clear')
        os.system ('git clone https://github.com/4shadoww/hakkuframework')
        os.system ('mv hakkuframework ~')

        termux_tool()
    elif termux == '28' :
        os.system ('clear')
        print ("Loading..........!")
        timeout(1)
        khaled()
        print ("done.....")
        os.system ('clear')
        os.system ('git clone https://github.com/gobline/translator.git')
        os.system ('mv translator.git ~')

        termux_tool()
    elif termux == '29' :
        os.system ('clear')
        print ("Loading..........!")
        timeout(1)
        khaled()
        print ("done.....")
        os.system ('clear')
        os.system ('git clone https://github.com/StreetSec/Gloom-Framework')
        os.system ('mv Gloom-Framework ~')
        termux_tool()
    elif termux == '30' :
        os.system ('clear')
        print ("Loading..........!")
        timeout(1)
        khaled()
        print ("done.....")
        os.system ('clear')
        os.system ('git clone https://github.com/wi-fi-analyzer/fluxion')
        os.system ('mv fluxion ~')

        termux_tool()
    elif termux == '31' :
        os.system ('clear')
        print ("Loading..........!")
        timeout(1)
        khaled()
        print ("done.....")
        os.system ('clear')
        os.system ('git clone https://github.com/LuaDist/unzip')
        os.system ('mv unzip ~')

        termux_tool()
    elif termux == '32' :
        os.system ('clear')
        print ("Loading..........!")
        timeout(1)
        khaled()
        print ("done.....")
        os.system ('clear')
        os.system ('git clone https://github.com/commixproject/commix.git')
        os.system ('mv commix.git ~')

        termux_tool()
    elif termux == '33' :
        os.system ('clear')
        print ("Loading..........!")
        timeout(1)
        khaled()
        print ("done.....")
        os.system ('clear')
        os.system ('git clone https://github.com/ihebski/angryFuzzer')
        os.system ('mv angryFuzzer ~')

        termux_tool()
    elif termux == '34' :
        os.system ('clear')
        print ("Loading..........!")
        timeout(1)
        khaled()
        print ("done.....")
        os.system ('clear')
        os.system ('git clone https://github.com/s0md3v/Breacher.git')
        os.system ('mv Breacher.git ~')

        termux_tool()
    elif termux == '35' :
        os.system ('clear')
        print ("Loading..........!")
        timeout(1)
        khaled()
        print ("done.....")
        os.system ('clear')
        os.system ('git clone https://github.com/Screetsec/Brutal')
        os.system ('mv Brutal ~')

        termux_tool()
    elif termux == '36' :
        os.system ('clear')
        print ("Loading..........!")
        timeout(1)
        khaled()
        print ("done.....")
        os.system ('clear')
        os.system ('git clone https://github.com/nxxxu/AutoPixieWps.git')
        os.system ('mv AutoPixieWps.git ~')

        termux_tool()
    elif termux == '37' :
        os.system ('clear')
        print ("Loading..........!")
        timeout(1)
        khaled()
        print ("done.....")
        os.system ('clear')
        os.system ('git clone https://github.com/Neo-Oli/termux-ubuntu')
        os.system ('mv termux-ubuntu.git ~')

        termux_tool()
    elif termux == '38' :
        os.system ('clear')
        print ("Loading..........!")
        timeout(1)
        khaled()
        print ("done.....")
        os.system ('clear')
        os.system ('git clone https://github.com/inconshreveable/ngrok.git')
        os.system ('mv ngrok.git ~')

        termux_tool()
    elif termux == '39' :
        os.system ('clear')
        print ("Loading..........!")
        timeout(1)
        khaled()
        print ("done.....")
        os.system ('clear')
        os.system ('git clone https://github.com/qmfrederik/dotnet-alpine-arm')
        os.system ('mv dotnet-alpine-arm ~')

        termux_tool()
    elif termux == '41' :
        os.system ('clear')
        print ("Loading..........!")
        timeout(1)
        khaled()
        print ("done.....")
        os.system ('clear')
        os.system ('git clone https://github.com/byt3bl33d3r/MITMf')
        os.system ('mv MITMf ~')

        termux_tool()
    elif termux == '42' :
        os.system ('clear')
        print ("Loading..........!")
        timeout(1)
        khaled()
        print ("done.....")
        os.system ('clear')
        os.system ('git clone https://github.com/wi-fi-analyzer/3vilTwinAttacker')
        os.system ('mv 3vilTwinAttacker ~')

        termux_tool()
    elif termux == '43' :
        os.system ('clear')
        print ("Loading..........!")
        timeout(1)
        khaled()
        print ("done.....")
        os.system ('clear')
        os.system ('git clone https://github.com/t6x/reaver-wps-fork-t6x.git')
        os.system ('mv reaver-wps-fork-t6x.git ~')

        termux_tool()
    elif termux == '44' :
        os.system ('clear')
        print ("Loading..........!")
        timeout(1)
        khaled()
        print ("done.....")
        os.system ('clear')
        os.system ('git clone https://github.com/SilentGhostX/HT-WPS-Breaker')
        os.system ('mv HT-WPS-Breaker ~')

        termux_tool()
    elif termux == '45' :
        khaled()
        os.system ('clear')
        os.system ('git clone https://github.com/achillean/shodan-python.git')
        khaled()
        os.system ('mv shodan-python.git `')
    elif termux == '46' :
        os.system ('clear')
        khaled()
        os.system ('clear')
        os.system ('git clone https://github.com/Xi4u7/A-Rat.git')
        khaled()
        os.system ('mv A-Rat.git ~')

        termux_tool()
    elif termux == '47' :
        os.system ('clear')
        khaled()
        os.system ('clear')
        os.system ('git clone https://github.com/beefproject/beef.git')
        khaled()
        os.system ('mv beef.gif ~')

        termux_tool()
    elif termux == '48' :
        os.system ('clear')
        khaled()
        os.system ('clear')
        os.system ('git clone https://github.com/Cabbagec/termux-ohmyzsh.git')
        khaled()
        os.system ('mv termux-ohmyzsh.git ~')
        termux_tool()
    elif termux == '49' :
        os.system ('clear')
        khaled()
        os.system ('clear')
        os.system ('git clone https://github.com/WattanaGaming/Spammer-Grab-1.git')
        khaled()
        os.system ('mv Spammer-Grab-1.git ~')
        termux_tool()
    elif termux == '50' :
        khaled()
        os.system ('clear')
        os.system ('git clone https://github.com/adi1090x/termux-style.git')
        khaled()
        os.system ('mv termux-style.git ~')
        termux_tool()

    elif termux == "51" :
        khaled()
        os.system ('clear')
        T_Done()
        os.system ('git clone https://github.com/Vairous7x/V7x-Tool.git')
        khaled()
        os.system ('mv termux-style.git ~')
        termux_tool()

    elif termux == "2" :
        os.system ('clear')
        print ("Loading..........!")
        timeout(1)
        khaled()
        print ("done.....")
        os.system ('clear')
        T_Done()
        os.system ('git clone https://github.com/Ranginang67/DarkFly-Tool.git')
        os.system ('mv DarkFly-Tool.git ~')
    elif termux == '99' :
        khaled()
        print ('Done...')
        os.system ('clear')
        home()
    else:
        khaled()
        os.system ('clear')
        termux_tool()

##########################################################################################################################################################

############################################################## lunix #####################################################################################

def lunix() :
    Done()
    time.sleep(0.7)
    os.system('clear')
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;34m||                      1. P.A.R.R.O.T                  ||")
    time.sleep(0.2)
    print ("|\033[0;31m|                                                      ||")
    time.sleep(0.2)
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;34m||                      2. KALI  LINUX                  ||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;34m||                      3. Kali NetHunter               ||") 
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;34m||                   4. BACK   BOX                      ||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;34m||                     5. C.E.N.T.O.S                   ||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;34m||                   6. OpenSUSE  Leap                  ||")
    time.sleep(0.2)
    print ("|\033[0;31m|                                                      ||")
    time.sleep(0.2)
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;34m||                       7. OpenSUSE Tumb               ||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;34m||                      8. Arch  linux                  ||") 
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;34m||                   9. Black Arch                      ||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;34m||                     10. D.E.B.I.A.N                  ||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;34m||                        99. main                      ||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    print (" ")

    linux = input ("\033[0;31mchoice 1,2,3,.... ====>> \033[0;36m")
    if linux == '1' :
        print (' ')
        print ("\033[1;31mBefore starting the installation,")
        print ("\033[1;93mmake sure that you have an empty space in your device not less than 500 MB so you do not get errors ")
        y = input ('Do you have 500 MB available...?  Y/n: ')
        if y == 'y' or y == 'Y' :
            print ('\033[1;92mOk....\033[1;31m Please Wait..')
            timeout(1)
            os.system ('pkg install wget openssl-tool proot -y && hash -r && wget https://raw.githubusercontent.com/EXALAB/AnLinux-Resources/master/Scripts/Installer/Parrot/parrot.sh && bash parrot.sh')
            print ('\033[1;31mDone....!')
            timeout(0.5)
            os.system ('clear')
            home()
        elif y == 'n' or y == 'N' :
            home()
        else:
            home()
    elif linux == '2' :
        print (' ')
        os.system ('clear')
        os.system ('pkg install wget openssl-tool proot -y && hash -r && wget https://raw.githubusercontent.com/EXALAB/AnLinux-Resources/master/Scripts/Installer/Kali/kali.sh && bash kali.sh')
        print ('\033[1;31mDone.....!')
        home()
    elif linux == '3' :
        os.system ('clear')
        os.system ('pkg install wget openssl-tool proot -y && hash -r && wget https://raw.githubusercontent.com/EXALAB/AnLinux-Resources/master/Scripts/Installer/Nethunter/nethunter.sh && bash nethunter.sh')
        home()
    elif linux == '4' :
        os.system ('clear')
        os.system ('pkg install wget openssl-tool proot -y && hash -r && wget https://raw.githubusercontent.com/EXALAB/AnLinux-Resources/master/Scripts/Installer/BackBox/backbox.sh && bash backbox.sh')
        home()
    elif linux == '5' :
        os.system ('clear')
        os.system ('pkg install wget openssl-tool proot tar -y && hash -r && wget https://raw.githubusercontent.com/EXALAB/AnLinux-Resources/master/Scripts/Installer/CentOS/centos.sh && bash centos.sh')
        home()
    elif linux == '6' :

        os.system ('clear')
        os.system ('pkg install wget openssl-tool proot tar -y && hash -r && wget https://raw.githubusercontent.com/EXALAB/AnLinux-Resources/master/Scripts/Installer/openSUSE/Leap/opensuse-leap.sh && bash opensuse-leap.sh')
        home()
    elif linux == '7' :
        os.system ('clear')
        os.system ('pkg install wget openssl-tool proot tar -y && hash -r && wget https://raw.githubusercontent.com/EXALAB/AnLinux-Resources/master/Scripts/Installer/openSUSE/Tumbleweed/opensuse-tumbleweed.sh && bash opensuse-tumbleweed.sh')
        home()
    elif linux == '8' :
        os.system ('clear')
        os.system ('pkg install wget openssl-tool proot tar -y && hash -r && wget https://raw.githubusercontent.com/EXALAB/AnLinux-Resources/master/Scripts/Installer/Arch/armhf/arch.sh && bash arch.sh')
        home()
    elif linux == '9' :
        os.system ('clear')
        os.system ('pacman-key --init && pacman-key --populate archlinuxarm && pacman -Sy --noconfirm curl && curl -O https://blackarch.org/strap.sh && chmod +x strap.sh && ./strap.sh')
        home()
    elif linux == '10' :
        os.system ('clear')
        os.system ('pkg install wget openssl-tool proot -y && hash -r && wget https://raw.githubusercontent.com/EXALAB/AnLinux-Resources/master/Scripts/Installer/Debian/debian.sh && bash debian.sh')
        home()
    elif linux == '99' :
        home()
    else:
        lunix()


################################################################################################################################################################

############################################################### ip #############################################################################################

def ip() :
    khaled()
    time.sleep(0.6)
    os.system('clear')
    V86k()
    print (" ")
    ii = input ("Enter target =========>>> ")
    T_Done()
    iip=socket.gethostbyname(ii)
    khaled()
    os.system('clear')
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    time.sleep(0.2)
    print ("\033[0;31m||    target==>  ",ii )
    time.sleep(0.2)
    print ("\033[0;34m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;31m||    ip ==> " , iip )
    time.sleep(0.2)
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    print (" ")
    print ("            1. again          2. main ")
    k = input ("\033[0;36mchoice 1 or 2 =======>> \033[0;31m")
    if k == "1" :
        ip()
    elif k == "2" :
        home()
################################################################################################################################################################

#################################################################### social ####################################################################################

def social () :
    print ("")
    Done()
    time.sleep(0.7)
    os.system('clear')
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;34m||                     1. weeman                        ||")
    time.sleep(0.2)
    print ("|\033[0;31m|            Create fake pages for hunti               ||")
    time.sleep(0.2)
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;34m||                       2.SELLPHISH                    ||")
    time.sleep(0.2)
    print ("\033[0;31m||     -Phishing Tool for 18 social media:              ||")
    print ("\033[0;31m||     Facebook, Snapchat, Twitter Wordpress,           ||")
    print ("\033[0;31m||     Yahoo,InstaFollowers, Microsoft                  ||")
    time.sleep(0.2)
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;34m||                      3.BLACK EYE                     ||") 
    time.sleep(0.2)
    print ("\033[0;31m||            The most complete Phishing Tool           ||")
    time.sleep(0.2)
    print ("\033[0;31m||            With 32 templates +1 customizable         ||")
    time.sleep(0.2)
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;34m||                   4.SOCIAL FISH                      ||")
    time.sleep(0.2)
    print ("\033[0;31m||     SocialFish ultimate phishing tool such as        ||")
    time.sleep(0.2)
    print ("\033[0;31m||     Twitter, stackoverflow, wordpress, github        ||")
    time.sleep(0.2)
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;34m||                     5.HIDDEN EYE                     ||")
    time.sleep(0.2)
    print ("\033[0;31m||         This tool is used by professionals only      ||")
    time.sleep(0.2)
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    time.sleep(0.2)
    print ("\033[0;31m||                      99. main                        ||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    print (" ")
    ww = input ("choice 1,2,3,........ ====>> ")
    if ww == "1" :
        khaled()
        os.system ('clear')
        T_Done()
        os.system ('git clone https://github.com/evait-security/weeman')
        os.system ('mv weeman ~')
        home()

    elif ww == "2" :
        khaled()  
        os.system ('clear')
        T_Done()
        os.system ('clear')
        os.system ('git clone https://github.com/thelinuxchoice/shellphish')
        os.system ('mv shellphish ~')
        home()

    elif ww == "3" :
        khaled()  
        os.system ('clear')
        T_Done()
        os.system ('clear')
        os.system ('git clone https://github.com/thelinuxchoice/blackeye')
        os.system ('mv blackeye ~')
        home()

    elif ww == "4" :
        os.system ('clear')
        os.system ('git clone https://github.com/UndeadSec/SocialFish.git')
        os.system ('mv SocialFish.git ~')
        home()

    elif ww == "5" :
        khaled()  
        os.system ('clear')
        T_Done()
        os.system ('clear')
        os.system ('git clone https://github.com/DarkSecDevelopers/HiddenEye.git')
        os.system ('mv HiddenEye.git ~')
        home()

    elif ww == "99" :
        khaled()
        home()

################################################################################################################################################################

#################################################################### information ###############################################################################

def information() :
    Done()
    time.sleep(0.7)
    os.system('clear')
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;34m||                      1. D-TECT                       ||")
    time.sleep(0.2)
    print ("|\033[0;31m|                                                      ||")
    time.sleep(0.2)
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;34m||                      2. RED_HAWK                     ||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;34m||                      3. thechoice                    ||") 
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;34m||                   4. pureblood                       ||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;34m||                     5. userrecon                     ||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;34m||                   6. ReconDog                        ||")
    time.sleep(0.2)
    print ("|\033[0;31m|                                                      ||")
    time.sleep(0.2)
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;34m||                       7. Infoga                      ||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;34m||                      8. Crips                        ||") 
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;34m||                   9. EvilURL.git                     ||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;34m||                     10. IPGeoLocation                ||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;34m||                        99. main                      ||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    print (" ")
    info = input ("\033[0;31mchoice 1,2,3,,.... =======>>> \033[0;36m")
    if info == '1' :
        T_Done()
        os.system ('clear')
        khaled()
        os.system ('git clone https://github.com/shawarkhanethicalhacker/D-TECT')
        os.system ('mv D-TECT ~')
        os.system ('clear')
        home()

    elif info == '2' :
        T_Done()
        os.system ('clear')
        khaled()

        os.system ('clear')
        os.system ('git clone https://github.com/Tuhinshubhra/RED_HAWK')
        os.system ('mv RED_HAWK ~')
        os.system ('clear')
        home()


    elif info == '3' :
        khaled()
        os.system ('clear')
        os.system ('git clone https://github.com/thelinuxchoice/thechoice')
        os.system ('mv thechoice ~')
        os.system ('clear')
        home()
    elif info == '4' :
        khaled()
        os.system ('clear')
        os.system ('git clone https://github.com/cr4shcod3/pureblood')
        os.system ('mv pureblood ~')
        home()
    elif info == '5' :
        khaled()
        os.system ('clear')
        os.system ('git clone https://github.com/thelinuxchoice/userrecon')
        os.system ('mv userrecon ~')
        home()
    elif info == '6' :
        khaled()
        os.system ('clear')
        os.system ('git clone https://github.com/UltimateHackers/ReconDog')
        os.system ('mv ReconDog ~')
        home()
    elif info == '7' :
        khaled()
        os.system ('clear')
        os.system ('git clone https://github.com/m4ll0k/Infoga')
        os.system ('mv Infoga ~')
        home()
    elif info == '8' :
        khaled()
        os.system ('clear')
        os.system ('git clone https://github.com/Manisso/Crips')
        os.system ('mv Crips ~')
        home()
    elif info == '9' :
        khaled()
        os.system ('clear')
        os.system ('git clone https://github.com/UndeadSec/EvilURL.git')
        os.system ('mv WvilURL.git ~')
        home()
    elif info == '10' :
        khaled()
        os.system ('clear')
        os.system ('git clone https://github.com/maldevel/IPGeoLocation')
        os.system ('mv IPGeoLocation ~')
        home()
    elif info == '99' :
        khaled()
        os.system ('clear')
        home()
    else:
        os.system ('clear')
        information()
################################################################################################################################################################

######################################################################### about ###############################################################################

def about() :
    Done()
    time.sleep(0.7)
    os.system('clear')
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;34m||        team name :   Vairous86k                      ||")
    time.sleep(0.2)
    print ("|\033[0;31m|                                                      ||")
    time.sleep(0.2)
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;34m||       team ====>>>    khaled                         ||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;34m||facebook ==> https://www.facebook.com/khaled.12.khaled||") 
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;34m||     telegram ==>> https://t.me/khaledVirus86         ||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;34m||                     99. main                         ||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    print (" ")
    ab = input ("\033[0;31mexit 99 ====>>> \033[0;36m")
    if ab == "99" :
        T_khaled()
        home()
    else :
        T_khaled()
        about()

################################################################################################################################################################

######################################################## hash ##########################################################################################

def hash() :
    khaled()
    time.sleep(0.6)
    os.system('clear')
    V86k()
    print (' ')
    compileall.compile_dir(khaled-hash)
    T_Done()
    Done()
#################################################################################################################################################################

######################################################### home #################################################################################################
def home() :
    Done()
    time.sleep(0.7)
    os.system('clear')
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;34m||                   1. termux tool                     ||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;34m||                   2. lunix on Android                ||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;34m||                   3. ip                              ||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;34m||                   4. social                          ||") 
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;34m||                   5. information                     ||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;34m||                   6. hash                            ||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;34m||                   7. About us                        ||")
    time.sleep(0.2)
    print ("\033[0;31m||                                                      ||")
    time.sleep(0.2)
    print ("\033[0;33m||||||||||||||||||||||||| khaled |||||||||||||||||||||||||")
    print (" ")
    h = input ("\033[0;36mchoice 1,2,........ =====>>> \033[0;32m")
    if h == "2" :
        khaled()
        os.system('clear')
        lunix()
    elif h == "3" :
        khaled() 
        os.system('clear') 
        ip()
    elif h == "4" :
        khaled() 
        os.system('clear') 
        social()
    elif h == "5" :
        khaled() 
        os.system('clear') 
        information()
        khaled() 
        os.system('clear') 
        termux_tool()
    elif h == "7" :
        khaled() 
        os.system('clear') 
        about()
    elif h == "6" :
        khaled() 
        os.system('clear') 
        hash()
        khaled()
    elif h == "1" :
        khaled()
        os.system('clear')
        termux_tool()
    else :
        Done()
        home()
###############################################################################################################################################

################################################# T_Done ###################################################################################

def T_Done() :
    Animation.Text(text='R#VP#8C#6B#k',
                   AT='(Done...)',
                   repeat=5,
    )

#############################################################################################################################################


################################################## T_khaled ###################################################################################

def T_khaled() :
    Animation.Loading(text='G#khaled......',
                 repeat=20,
    )

################################################################################################################################################ 




############################################################### Done ############################################################################

def Done() :
    Animation.DL(text='\033[0;31mDone ',
                 t=0.5,
    )

################################################################# khaled ########################################################################

def khaled() :
    Animation.DL(text='\033[0;31mkhaled ',
                 t=0.5,
    )

###################################################################### V86k ####################################################################

def V86k() :
    khaled()
    time.sleep(0.5)
    os.system('clear')
    print ("\033[0;31m _     _   _____   _____   _   _   ")
    time.sleep(0.2)
    print ("\033[0;32m| |   / / /  _  \ /  ___| | | / /  ")
    time.sleep(0.2)
    print ("\033[0;33m| |  / /  | |_| | | |___  | |/ /   ")
    time.sleep(0.2)
    print ("\033[0;34m| | / /   }  _  { |  _  \ | |\ \   ")
    time.sleep(0.2)
    print ("\033[0;35m| |/ /    | |_| | | |_| | | | \ \  ")
    time.sleep(0.2)
    print ("\033[0;37m|___/     \_____/ \_____/ |_|  \_\ ")
    time.sleep(0.2)
    print (" ")
    print (" ")

############################################################### password ########################################################################
def pas() :
    V86k()
    p=input ("enter your password =====>>> ")
    if p=="V86k" :
        T_Done()
        home()
    else :
        print ("                         EROR                 ")
        time.sleep(0.6)
        os.system('clear')
        pas()

pas()
